### ISSUE TITLE
Object has no method updatedAttributes

### ISSUE THREAD

**Issue by drewbharris** [imlucas/node-mambo#3]
TypeError: Object #<Table> has no method 'updatedAttributes'
      at Table.returnValues (/Users/drew/Documents/exfm/shuffle/node_modules/magneto/lib/table.js:406:28)
      at Table.updateItem (/Users/drew/Documents/exfm/shuffle/node_modules/magneto/lib/table.js:191:26)
      at Object.forEach.DB.(anonymous function) [as updateItem](/Users/drew/Documents/exfm/shuffle/node_modules/magneto/lib/db.js:146:14)
      at Object.DB.process (/Users/drew/Documents/exfm/shuffle/node_modules/magneto/lib/db.js:12:31)
      at IncomingMessage.<anonymous> (/Users/drew/Documents/exfm/shuffle/node_modules/magneto/lib/server.js:46:23)
      at IncomingMessage.EventEmitter.emit (events.js:85:17)
      at IncomingMessage._emitEnd (http.js:366:10)
      at HTTPParser.parserOnMessageComplete [as onMessageComplete](http.js:149:23)
      at Socket.socket.ondata (http.js:1690:22)
      at TCP.onread (net.js:402:27)

**Comment by imlucas** [comment]
Magneto issue.  Moving over there.
