### ISSUE TITLE
Error on this.conect.apply - attempting to re-use lastConnection

### ISSUE THREAD

**Issue by jwicks** [imlucas/node-mambo#50]
Here is the error:

``` bash
/Users/jwicks/Documents/workspaces/project/node_modules/mambo/index.js:43
        this.conect.apply(this, module.exports.lastConnection);
                    ^
TypeError: Cannot call method 'apply' of undefined
    at new Model (/Users/jwicks/Documents/workspaces/project/node_modules/mambo/index.js:43:21)
    at Object.<anonymous> (/Users/jwicks/Documents/workspaces/project/server.js:53:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:3
>> application exited with code 8
```

Here is my code in app.js.  I am attempted to connect mambo once as recommended here - http://exfm.github.io/node-mambo/#connecting-to-dynamo . And then have the models re-use the connection.  Let me know if this is not recommended

``` javascript
var mambo = require('mambo')
  , Schema = mambo.Schema
  , StringField = mambo.StringField;

mambo.connect('key', 'secret', 'prefix', 'us-east-1');

var UserSchema = new Schema('User', 'user', 'id', {
    'id': StringField,
    'firstName': StringField
});

var User = new mambo.Model(UserSchema);
```

When I fix the conect typo in mambo/index.js line 43 to:

``` javascript
this.connect.apply(this, module.exports.lastConnection);
```

Everything works.  Should I submit a pull request?

**Comment by imlucas** [comment]
Yes please!  Apologies not quite sure how i missed this... time to check some gmail filters.
